[package]
name = "magolor"
version = "0.1.0"
edition = "2021"

[lib]
name = "magolor"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "magolor"
path = "src/main.rs"

[dependencies]
logos = "0.14"
anyhow = "1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
